Repository SunbrightCreators/Moiso-Front, pull requests merged in 2025-08, with the labels that each got.

#2 PWA 프로젝트 환경 설정
  .env.example
  .github/ISSUE_TEMPLATE/BUG_REPORT_BRIEF.md
  .github/ISSUE_TEMPLATE/BUG_REPORT_DETAIL.md
  .github/ISSUE_TEMPLATE/TODO.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierrc.json
  README.md
  netlify.toml
  package-lock.json
  package.json
  public/index.html
  public/logo.svg
  public/logo_512.png
  public/manifest.json
  public/robots.txt
  public/screenshot_narrow.svg
  public/screenshot_wide.svg
  public/service-worker.js
  src/Router.jsx
  src/apis/example.js
  src/apis/instance.js
  src/apis/interceptor.js
  src/assets/icons/.gitkeep
  src/components/common/.gitkeep
  src/hooks/.gitkeep
  src/index.jsx
  src/pages/.gitkeep
  src/serviceWorkerRegistration.js
  src/stores/example.js
  src/styles/global.js
  src/styles/reset.css
  src/styles/theme.js
Labels: feature✨, setting⚙

#6 Chakra UI 라이브러리 환경 설정
  package-lock.json
  package.json
  src/index.jsx
  src/styles/global.js
  src/styles/reset.css
  src/styles/snippets/provider.jsx
  src/styles/snippets/toaster.jsx
  src/styles/snippets/tooltip.jsx
  src/styles/theme.js
Labels: feature✨, setting⚙

#29 InputSearch
  src/assets/icons/search.svg
  src/assets/icons/x.svg
  src/components/common/InputSearch.jsx
Labels: design💄, feature✨

#35 Timepicker
  src/components/common/Timepicker.jsx
Labels: design💄, feature✨

#36 Enum, 환경변수, ROUTE_PATH 상수 추가
  src/apis/instance.js
  src/constants/enum.js
  src/constants/env.js
  src/constants/route.js
  src/service-workers/subscribePush.js
Labels: design💄, feature✨

#41 제안 AI 추천 페이지 퍼블리싱
  src/assets/icons/EmptyState.svg
  src/assets/icons/EmptyState_s.svg
  src/assets/icons/heart_default.svg
  src/assets/icons/heart_disabled.svg
  src/assets/icons/heart_pressed.svg
  src/assets/icons/scrap_default.svg
  src/assets/icons/scrap_pressed.svg
  src/pages/ProposalRecPage.jsx
Labels: design💄, feature✨

#17 Bottomsheet
  public/index.html
  src/components/common/Bottomsheet.jsx
  src/index.jsx
  src/stores/useModalBottomsheetStore.js
Labels: design💄, feature✨

#50 PWA 관련 이미지 교체
  public/logo.svg
  public/logo_512.png
  public/screenshot_narrow.svg
  public/screenshot_wide.svg
Labels: design💄, feature✨

#37 랜딩, 로그인, 회원가입, 온보딩 페이지 퍼블리싱
  src/assets/icons/Foundergif.gif
  src/assets/icons/Proposergif.gif
  src/assets/icons/Right part.svg
  src/assets/icons/logo1.svg
  src/assets/icons/심볼.svg
  src/pages/FounderTarget.jsx
  src/pages/FounderTime.jsx
  src/pages/LandingPage.jsx
  src/pages/LogInPage.jsx
  src/pages/NeighborhoodSettingsPage.jsx
  src/pages/OnBardingSelect.jsx
  src/pages/SignUpIndex.jsx
  src/pages/SignUpPage1.jsx
  src/pages/SignUpPage2.jsx
  src/pages/WelcomePage.jsx
Labels: design💄, feature✨

#56 메타데이터 수정
  public/index.html
  public/manifest.json
Labels: design💄, refactor♻️

#72 로그인 페이지 API 연결
  src/pages/LogInPage.jsx
Labels: development🔨, feature✨

#77 로그인하고 정보를 저장해야 함
  src/apis/interceptor.js
  src/pages/LogInPage.jsx
Labels: bug🐛, development🔨

#53 제안하기 등록 퍼블리싱
  src/pages/PlaceSearchPage.jsx
  src/pages/ProposalCreatePage.jsx
  src/pages/ProposalIndex.jsx
Labels: design💄, feature✨

#79 버그 수정
  src/pages/MyPage.jsx
  src/pages/ProposalCreatePage.jsx
  src/pages/RewardPage.jsx
  src/pages/SignUpPage1.jsx
Labels: bug🐛, design💄
