Repository SunbrightCreators/Moiso-Front, pull requests merged in 2025-09, with the labels that each got.

#85 네이버 클라우드 환경변수 추가
  .env.example
  src/constants/env.js
Labels: feature✨, setting⚙

#83 나의 스크랩 페이지 퍼블리싱
  src/pages/MyScrap.jsx
Labels: design💄, feature✨

#87 제안글 지도 탐색 페이지 (ProposalListPage) 오류 해결
  src/components/proposal/ProposalList.jsx
  src/pages/ProposalListPage.jsx
  src/pages/WelcomePage.jsx
Labels: bug🐛, design💄

#112 TanStack Query 도입
  package-lock.json
  package.json
  src/apis/accounts.js
  src/apis/example.js
  src/apis/fundings.js
  src/apis/maps.js
  src/apis/proposals.js
  src/apis/recommendations.js
  src/constants/enum.js
  src/index.jsx
Labels: development🔨, feature✨

#113 참조 오류, 훅 사용 위치 오류 해결
  src/apis/fundings.js
  src/apis/proposals.js
  src/pages/login/LoginPage.jsx
  src/pages/proposal/ProposalMapPage.jsx
Labels: bug🐛, development🔨

#114 배포
  src/apis/fundings.js
  src/apis/proposals.js
  src/pages/login/LoginPage.jsx
  src/pages/proposal/ProposalMapPage.jsx
Labels: bug🐛, deploy🚀

#108 BottomNavigation 수정
  src/components/common/navigation/BottomNavigation.jsx
  src/pages/my/MyPage.jsx
  src/pages/recommendation-proposal/ProposalRecPage.jsx
Labels: design💄, refactor♻️

#115 NeighborhoodSettingsPage 동네 인증 기능 구현
  src/assets/icons/target.svg
  src/pages/signup/NeighborhoodSettingsPage.jsx
Labels: development🔨, feature✨

#103 Emptystate 수정
  src/assets/EmptyProposer.svg
  src/assets/EmptyReward.svg
  src/assets/EmptyState (5).svg
  src/assets/EmptyState.svg
  src/assets/EmptyState_s.svg
  src/assets/EmptySupporter.svg
  src/assets/icons/frown.svg
  src/assets/icons/rewardempty.svg
  src/pages/my-funding/MyFundingPage.jsx
  src/pages/my-proposal/MyProposalPage.jsx
  src/pages/reward/RewardPage.jsx
Labels: design💄, refactor♻️

#126 RewardPage API 연결
  src/pages/reward/RewardPage.jsx
Labels: deploy🚀, feature✨

#135 Myscrap Page api연결
  src/pages/my-scrap/MyScrap.jsx
Labels: development🔨, feature✨

#136 제안글 작성 - Radius 및 위치 설정 (#74)
  src/components/common/navigation/TopNavigation.jsx
  src/pages/proposal-create/CreateProposalMapPage.jsx
  src/pages/proposal-create/PlaceSearchPage.jsx
  src/pages/proposal-create/ProposalCreatePage.jsx
  src/pages/proposal-create/index.jsx
Labels: design💄

#145 MyProposal, MyFundingpage api 연결
  src/apis/fundings.js
  src/apis/proposals.js
  src/pages/my-funding/MyFundingPage.jsx
  src/pages/my-proposal/MyProposalPage.jsx
Labels: deploy🚀, feature✨

#152 지도 요청 URL 오타 수정
  src/apis/NaverMapLoader.js
Labels: bug🐛, development🔨
